In [1]:
import numpy as np

In [2]:
lst=[1,2,3,4,5]

In [3]:
lst

[1, 2, 3, 4, 5]

In [6]:
arraylst=np.array(lst)

In [7]:
arraylst

array([1, 2, 3, 4, 5])

In [21]:
def result(arraylst,n,increasing):
    res=[]
    for i in arraylst:
        for j in range(n):
            if increasing==False:
                res.append(i**j)
            else:
                res.append(i**(n-j-1))
    return np.matrix(res).reshape(len(arraylst),n)

In [22]:
print(result(arraylst,5,True))

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [23]:
print(result(arraylst,5,False))

[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]


Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [24]:
inputarray=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] )

In [35]:
len(inputarray)

13

In [43]:
for i in range(len(inputarray)-3):
    print('y_',i,': ',(inputarray[i]+inputarray[i+1]+inputarray[i+2])/3)
        

y_ 0 :  5.0
y_ 1 :  4.666666666666667
y_ 2 :  5.666666666666667
y_ 3 :  6.666666666666667
y_ 4 :  9.666666666666666
y_ 5 :  28.666666666666668
y_ 6 :  49.333333333333336
y_ 7 :  72.66666666666667
y_ 8 :  84.0
y_ 9 :  93.33333333333333
